using System;
using DevExpress.Persistent.Base;
using Xpand.Source.Extensions.XAF.XafApplication;

namespace Xpand.XAF.Modules.ModelMapper.Configuration{
    [AttributeUsage(AttributeTargets.Field)]
    public class MapPlatformAttribute:Attribute{
        internal MapPlatformAttribute(Platform platform){
            Platform = platform.ToString();
        }

        public string Platform{ get; }
    }

    public enum PredefinedMap{
        None,

        [MapPlatform(Platform.Win)]
        [ImageName(@"Office2013\Grid_16x16")]
        GridView,
        [MapPlatform(Platform.Win)]
        [ImageName(@"Office2013\Grid_16x16")]
        GridColumn,
        [MapPlatform(Platform.Win)]
        [ImageName("GridBandedRows_16x16")]
        AdvBandedGridView,
        [MapPlatform(Platform.Win)]
        [ImageName("GridBandedRows_16x16")]
        BandedGridColumn,
        [MapPlatform(Platform.Win)]
        [ImageName(@"GrayScaleImages\MoreLayoutOptions_16x16")]
        XafLayoutControl,
        [MapPlatform(Platform.Win)]
        [ImageName(@"Office2013\AlignVerticalCenter_16x16")]
        SplitContainerControl,
        [MapPlatform(Platform.Win)]
        [ImageName(@"re-layout")]
        LayoutView,
        [MapPlatform(Platform.Win)]
        [ImageName(@"re-layout")]
        LayoutViewColumn,
        [MapPlatform(Platform.Win)]
        [ImageName(@"re-layout")]
        LayoutControlGroup,
        [MapPlatform(Platform.Win)]
        [ImageName(@"TreeView_16x16")]
        TreeList,
        [MapPlatform(Platform.Win)]
        [ImageName(@"TreeView_16x16")]
        TreeListColumn,
        
        [MapPlatform(Platform.Win)]
        [ImageName(@"Action_CreateDashboard")]
        DashboardDesigner,
        [MapPlatform(Platform.Win)]
        [ImageName(@"HorizontalAxisWithoutLabeling_16x16")]
        LabelControl,
        [MapPlatform(Platform.Win)]
        [ImageName(@"RichEditBookmark_16x16")]
        RichEditControl,
        [MapPlatform(Platform.Win)]
        [ImageName(@"Action_CreateDashboard")]
        DashboardViewer,
        [MapPlatform(Platform.Web)]
        [ImageName(@"Action_CreateDashboard")]
        ASPxDashboard,
        [MapPlatform(Platform.Win)]

        RepositoryItem,
        [MapPlatform(Platform.Win)]
        [ImageName(@"WithTextWrapping_TopLeft_16x16")]
        RepositoryItemTextEdit,
        [MapPlatform(Platform.Win)]
        [ImageName(@"Action_Debug_Start")]
        RepositoryItemButtonEdit,
        [MapPlatform(Platform.Win)]
        [ImageName(@"ComboBox_16x16")]
        RepositoryItemComboBox,
        [MapPlatform(Platform.Win)]
        [ImageName(@"ADateOccurring_16x16")]
        RepositoryItemDateEdit,
        [MapPlatform(Platform.Win)]
        [ImageName(@"HighlightField_16x16")]
        RepositoryFieldPicker,
        [MapPlatform(Platform.Win)]
        RepositoryItemPopupExpressionEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemPopupCriteriaEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemImageComboBox,
        [MapPlatform(Platform.Win)]
        RepositoryItemBaseSpinEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemSpinEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemObjectEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemMemoEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemLookupEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemProtectedContentTextEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemBlobBaseEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemRtfEditEx,
        [MapPlatform(Platform.Win)]
        RepositoryItemHyperLinkEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemPictureEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemCalcEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemCheckedComboBoxEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemColorEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemFontEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemLookUpEditBase,
        [MapPlatform(Platform.Win)]
        RepositoryItemMemoExEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemMRUEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemBaseProgressBar,
        [MapPlatform(Platform.Win)]
        RepositoryItemMarqueeProgressBar,
        [MapPlatform(Platform.Win)]
        RepositoryItemProgressBar,
        [MapPlatform(Platform.Win)]
        RepositoryItemRadioGroup,
        [MapPlatform(Platform.Win)]
        RepositoryItemTrackBar,
        [MapPlatform(Platform.Win)]
        RepositoryItemRangeTrackBar,
        [MapPlatform(Platform.Win)]
        RepositoryItemTimeEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemZoomTrackBar,
        [MapPlatform(Platform.Win)]
        RepositoryItemImageEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemPopupContainerEdit,
        [MapPlatform(Platform.Win)]
        RepositoryItemPopupBase,
        [MapPlatform(Platform.Win)]
        RepositoryItemPopupBaseAutoSearchEdit,
        [MapPlatform(Platform.Win)]
        [ImageName("Calendar_16x16")]
        SchedulerControl,
        
        [MapPlatform(Platform.Win)]
        [ImageName("BOPivotChart_16x16")]
        PivotGridControl,
        [MapPlatform(Platform.Win)]
        [ImageName("BOPivotChart_16x16")]
        PivotGridField,
        [MapPlatform(Platform.Win)]
        [ImageName(@"GrayScaleImages\Chart_16x16")]
        ChartControl,
        [MapPlatform(Platform.Win)]
        ChartControlDiagram,
        [MapPlatform(Platform.Win)]
        ChartControlDiagram3D,
        [MapPlatform(Platform.Win)]
        ChartControlFunnelDiagram3D,
        [MapPlatform(Platform.Win)]
        ChartControlXYDiagram3D,
        [MapPlatform(Platform.Win)]
        ChartControlRadarDiagram,
        [MapPlatform(Platform.Win)]
        ChartControlSimpleDiagram3D,
        [MapPlatform(Platform.Win)]
        ChartControlPolarDiagram,
        [MapPlatform(Platform.Win)]
        ChartControlXYDiagram2D,
        [MapPlatform(Platform.Win)]
        ChartControlSwiftPlotDiagram,
        [MapPlatform(Platform.Win)]
        ChartControlXYDiagram,
        [MapPlatform(Platform.Win)]
        ChartControlGanttDiagram,
        [MapPlatform(Platform.Web)]
        [ImageName("Grid_16x16")]
        ASPxGridView,
        [MapPlatform(Platform.Web)]
        [ImageName("Grid_16x16")]
        GridViewDataColumn,
        [MapPlatform(Platform.Web)]
        ASPxHtmlEditor,
        [MapPlatform(Platform.Web)]
        [ImageName("Calendar_16x16")]
        ASPxScheduler,
        [MapPlatform(Platform.Web)]
        ASPxUploadControl,
        [MapPlatform(Platform.Web)]
        [ImageName(@"DevAV\ViewSetting_16x16")]
        ASPxPopupControl,
        [MapPlatform(Platform.Web)]
        ASPxDateEdit,
        [MapPlatform(Platform.Web)]
        ASPxHyperLink,
        [MapPlatform(Platform.Web)]
        ASPxLookupDropDownEdit,
        [MapPlatform(Platform.Web)]
        ASPxLookupFindEdit,
        [MapPlatform(Platform.Web)]
        ASPxSpinEdit,
        [MapPlatform(Platform.Web)]
        ASPxTokenBox,
        [MapPlatform(Platform.Web)]
        ASPxComboBox
    }
}