using DevExpress.ExpressApp;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
using DevExpress.ExpressApp.Model.Core;

namespace Xpand.Extensions.XAF.Model{
    public static partial class ModelExtensions{
        public static IModelClass FindModelClass(this IModelApplication modelApplication, System.Type objectType){
            var model = modelApplication;
            IModelClass modelClass = null;
            if ((objectType != null) && model?.BOModel != null){
                ITypeInfo typeInfo = XafTypesInfo.Instance.FindTypeInfo(objectType);
                modelClass = model.BOModel.GetClass(typeInfo != null ? typeInfo.Type : objectType);
                if (modelClass == null){
                    System.Type interfaceType = ModelAutoGeneratedRuleNodesHelper.GetAssociatedDomainComponentType(objectType);
                    if (interfaceType != null){
                        modelClass = model.BOModel.GetClass(interfaceType);
                    }
                }
            }

            return modelClass;
        }
    }
}